openapi: 3.0.3
info:
  title: JUST_MOCKING
  version: 1.0.0
  description: >+
    Node 18 based Express server. Here we have handled unit tests. We have also
    implemented Commitizen, Eslint, Prettier, Husky and Mocha. 

     - `prettier` - For formatting the code. 

     - `commitizen` - For uniforming the commits. 

     - `eslint` - For uniforming the code style. 

     - `husky` - For checking the lint errors and prevent the difference in code writing style. 

     - `mocha`- For testing the code 

  contact:
    name: IppoPay
    email: support@ippopay.com
  license:
    name: Appache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://ippouat.ippopay.com/api/v1/ippo-partner
    description: Staging Server
tags:
  - name: Merchant
    description: Merchant Related Routes
  - name: Store
    description: Store Related Routes
  - name: KYC
    description: KYC and Business Proof Validation Routes
  - name: VPA
    description: VPA Related Routes
  - name: Transaction
    description: Transaction Related Routes
paths:
  /merchant/create:
    post:
      tags:
        - Merchant
      summary: To create Merchant
      requestBody:
        description: >-
          Legal name(Legal Name of the Business or Merchant), brand name(Display
          name of the Business), merchant type, location and mobile number is
          mandatory. email is optional.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/merchant_create"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Merchant created successfully
                data:
                  merchant_id: JNFG08NgFLKg
                  legal_name: Momo Foods Pvt Ltd
                  brand_name: Wow! Momo
                  mobile_number: "9988776767"
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /vpa/create:
    post:
      tags:
        - VPA
      summary: >-
        To create VPA. Penny Drop Verification is done here. KYC should be
        completed before creating VPA.
      requestBody:
        description: >-
          Merchant ID, Store ID, VPA Name (For Display Purpose), VPA (VPA ID),
          Account Number, Account Holder Name and IFSC are mandatory.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/vpa_create"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: VPA created successfully
                data:
                  vpa_name: Wow! Momo - Ashok Nagar
                  vpa: ipponinjaxxxxxxxx@icici
                  bank:
                    account_number: xxxxxxxx9876
                    ifsc: xxxx00000001
                    beneficiary_name: Wow Foods Pvt Ltd
        "400":
          description: ""
          content:
            application/json:
              example:
                success: false
                message: Bad Request
  /vpa/update/{merchantId}:
    post:
      tags:
        - VPA
      summary: To update bank account number for the VPA
      requestBody:
        description: >-
          VPA ID, Store ID, Account Number, IFSC Code, and Account Holder Name
          are mandatory.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/vpa_update"
        required: true
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to update VPA
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Account number updated successfully
                data:
                  vpa_name: Wow! Momo - Ashok Nagar
                  vpa: ipponinjaxxxxxxxx@icici
                  bank:
                    account_number: xxxxxxxx9876
                    ifsc: xxxx00000001
                    beneficiary_name: Wow Foods Pvt Ltd
        "400":
          description: ""
          content:
            application/json:
              example:
                success: false
                message: Bad Request
  /store/create/{merchantId}:
    post:
      tags:
        - Store
      summary: To create Store
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to create Store
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      requestBody:
        description: >-
          Store name, MCC, are mandatory. If the merchant and store has the same
          address, is_same_merchant_address has to be checked (i.e) true. If it
          is not checked, the location is mandatory.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/store_create"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Store Created Successfully!
                data:
                  merchant_id: sBLC9KuBvv
                  store_id: Ikpsjnbhv
                  legal_name: Momo Foods Pvt Ltd
                  brand_name: Wow! Momo - Ashok Nagar
                  store_name: Store 1 Momo
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /transaction/list/{merchantId}:
    get:
      tags:
        - Transaction
      summary: To list transactions of the merchant
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to list transaction
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
        - name: limit
          in: query
          description: For pagination purpose
          schema:
            type: string
          example: "2"
        - name: page
          in: query
          description: For pagination purpose
          schema:
            type: string
          example: "2"
        - name: mode
          in: query
          description: Payment mode. Should have values upi, cash
          schema:
            type: string
          example: upi
        - name: from_time
          in: query
          description: >-
            To list the transaction from this date. NOTE: At present, the system
            allows access to transaction records within a maximum range of only
            31 days from any date. The date format is YYYY-MM-DD.
          schema:
            type: string
          example: "2023-04-06"
        - name: to_time
          in: query
          description: >-
            To list the transaction till this date. NOTE: At present, the system
            allows access to transaction records within a maximum range of only
            31 days. The date format is YYYY-MM-DD.
          schema:
            type: string
          example: "2023-05-04"
        - name: date_option
          in: query
          description: Date option includes 'today', 'yesterday', 'weekly', 'monthly'
          schema:
            type: string
          example: today
        - name: status
          in: query
          description: >-
            To list transactions based on the status of the transaction. Should
            have values 'success', 'pending', 'failure'.
          schema:
            type: string
          example: success
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Transaction lists are
                data:
                  sales_by_mode:
                    cash:
                      total: 0
                      count: 0
                    card:
                      total: 0
                      count: 0
                    upi:
                      total: 600
                      count: 2
                  total_sales:
                    - total: 600
                      count: 2
                  transaction_details:
                    - merchant_id: 6RSahMApDw
                      store_id: 6RSahMApDw
                      transaction_id: "4833812123"
                      amount: 300
                      mode: UPI
                      transaction_status: success
                      transaction_date: "2023-04-25T10:35:48.788Z"
                    - merchant_id: 6RSahMApDw
                      store_id: 6RSahMApDw
                      transaction_id: "4833812133"
                      amount: 300
                      mode: UPI
                      transaction_status: success
                      transaction_date: "2023-04-25T10:35:48.788Z"
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /transaction/details/{merchantId}/{transactionId}:
    get:
      tags:
        - Transaction
      summary: To view the details of a transaction of the merchant
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to view transaction
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
        - name: transactionId
          in: path
          description: ID of transaction to view transaction
          required: true
          schema:
            type: string
          example: hjgfdhsd
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Transaction Details
                data:
                  merchant_id: 6RSahMApDw
                  store_id: 6RSahMApDw
                  transaction_id: "4833812133"
                  amount: 300
                  mode: upi
                  transaction_status: success
                  details:
                    type: ecollect
                    amount: "300.00"
                    status: success
                    payer_vpa: s**************s
                    payee_vpa: ip************i
                    app: gpay
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /kyc-validate/address-proof/aadhaar/{merchantId}:
    post:
      tags:
        - hidden
      summary: To request OTP for Aadhaar Verification
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to submit documents
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      requestBody:
        description: Aadhaar number and Document type is mandatory.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/aadhar_request_otp"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: >-
                  Aadhaar verification started. OTP sent your registered mobile
                  number is valid for another 10 minutes.
                data:
                  aadhaar_number: 718**************
                  transaction_id: 50B*************************1357
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /kyc-validate/aadhaar-otp-validate/{merchantId}:
    post:
      tags:
        - hidden
      summary: To verify the One Time Password for Aadhar
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to submit documents
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      requestBody:
        description: >-
          Transaction ID is mandatory which is from response of the request otp
          route. OTP and Aadhaar Number is mandatory.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/otp_verification"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Aadhaar data retrieved successfully.
                data:
                  aadhaar_number: 6***********3
                  name: Y******
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /kyc-validate/address-proofs/{merchantId}:
    post:
      tags:
        - KYC
      summary: >-
        To validate and submit other address proofs like passport, driver's
        license, and voter ID
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to submit documents
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      requestBody:
        description: >-
          Document Types should be license, voterId, or passport. If License is
          the given proof, please include date of birth. And if the selected
          document is passport, name and date of birth should be sent.
          Images/PDFs should be uploaded.
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/voter_id"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: "*** Submitted Successfully!"
                data:
                  "***": "********1"
                  name: "S*****in "
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /kyc-validate/pan/{merchantId}:
    post:
      tags:
        - KYC
      summary: To validate and submit PAN card.
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to submit documents
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      requestBody:
        description: PAN number, document type, and Image/PDF to be uploaded.
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/pan"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Pan Submitted Successfully!
                data:
                  pan_number: J*********A
                  name: S*******
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /kyc-validate/business-proof/{merchantId}:
    post:
      tags:
        - KYC
      summary: To submit business proofs
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to submit documents
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      requestBody:
        description: >-
          Document Number, Document Type (From the list), and PDFs/Images should
          be uploaded.
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/business_proof"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Documents Submitted Successfully!
                data:
                  document_type: >-
                    List of partners of LLP with name, date of birth and
                    address. List to match with MCA website
                  document_no: 12*******12
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
  /kyc-validate/aadhaar/{merchantId}:
    post:
      tags:
        - KYC
      summary: To submit aadhaar details
      parameters:
        - name: merchantId
          in: path
          description: ID of merchant to submit aadhaar details
          required: true
          schema:
            type: string
          example: sBLC9KuBvv
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/aadhaar_details"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              example:
                success: true
                message: Aadhaar Submitted Successfully!
                data:
                  aadhaar_number: XXXXXXXX5428
                  name: Purnendra Ahirwar
        "400":
          description: ""
          content:
            application/json:
              example:
                status: false
                message: Bad Request
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    merchant_create:
      required:
        - legal_name
        - brand_name
        - mobile_number
        - merchant_type
        - location
      type: object
      properties:
        legal_name:
          type: string
          example: Momo Foods Pvt Ltd
        brand_name:
          type: string
          example: Wow! Momo
        mobile_number:
          type: string
          example: "9988776767"
        email:
          type: string
          example: info@wowmomo.com
        merchant_type:
          type: string
          example: partnership
        location:
          type: object
          required:
            - address
            - area
            - city
            - state
            - pin_code
            - latlong
          properties:
            address:
              type: string
              example: Balaji Building, 36, 100 Feet Rd, Sector 10
            area:
              type: string
              example: Ashok Nagar
            city:
              type: string
              example: Chennai
            state:
              type: string
              example: Tamil Nadu
            pin_code:
              type: string
              example: "600083"
            latlong:
              type: string
              example: 13.0362588,80.2119896
    vpa_create:
      required:
        - merchant_id
        - store_id
        - vpa_name
        - vpa
        - bank
      type: object
      properties:
        merchant_id:
          type: string
          example: JNFG08NgFLKg
        store_id:
          type: string
          example: JNFG08NgFLKg
        vpa_name:
          type: string
          example: Wow! Momo - Ashok Nagar
        vpa:
          type: string
          example: ipponinjaxxxxxxxx@icici
        bank:
          type: object
          required:
            - account_number
            - ifsc
            - account_holder_name
          properties:
            account_number:
              type: string
              example: "12345678909876"
            ifsc:
              type: string
              example: xxxx00000001
            account_holder_name:
              type: string
              example: WOW MOMO
    vpa_update:
      required:
        - vpa_id
        - store_id
        - bank
      type: object
      properties:
        vpa_id:
          type: string
          example: ipponinjaxxxxxxxx@icici
        store_id:
          type: string
          example: sBLC9KuBvv
        bank:
          type: object
          required:
            - account_number
            - ifsc
            - account_holder_name
          properties:
            account_number:
              type: string
              example: "12345678909876"
            ifsc:
              type: string
              example: xxxx00000001
            account_holder_name:
              type: string
              example: WOW MOMO
    store_create:
      required:
        - store_name
        - mcc
        - is_same_merchant_address
      type: object
      properties:
        store_name:
          type: string
          example: store 1 Momo
        location:
          type: object
          properties:
            address:
              type: string
              example: Balaji Building, 36, 100 Feet Rd, Sector 10
            area:
              type: string
              example: Ashok Nagar
            city:
              type: string
              example: Chennai
            state:
              type: string
              example: Tamil Nadu
            pin_code:
              type: string
              example: "600083"
            latlong:
              type: string
              example: 13.0362588,80.2119896
        mcc:
          type: string
          example: "0824"
        is_same_merchant_address:
          type: boolean
          example: "false"
    aadhar_request_otp:
      required:
        - number
        - document_type
      type: object
      properties:
        number:
          type: string
          example: 7**********1
        document_type:
          type: string
          example: aadhaar
    otp_verification:
      required:
        - transaction_id
        - otp
        - number
      type: object
      properties:
        transaction_id:
          type: string
          example: GDSGD762381791EDJGFKJAASD
        otp:
          type: string
          example: "234434"
        number:
          type: string
          example: 7**********1
    passport:
      required:
        - uploadFile
        - number
        - document_type
        - date_of_birth
        - name
      type: object
      properties:
        number:
          type: string
          example: 7**********1
        document_type:
          type: string
          example: passport
        date_of_birth:
          type: string
          example: YYYY-MM-DD
        name:
          type: string
          example: Anna
        uploadFile:
          type: string
          format: binary
    voter_id:
      required:
        - uploadFile
        - number
        - document_type
      type: object
      properties:
        number:
          type: string
          example: 7**********1
        document_type:
          type: string
          example: voterId
        date_of_birth:
          type: string
          example: YYYY-MM-DD
        name:
          type: string
          example: Anna
        uploadFile:
          type: string
          format: binary
    license:
      required:
        - uploadFile
        - number
        - document_type
        - date_of_birth
      type: object
      properties:
        number:
          type: string
          example: 7**********1
        document_type:
          type: string
          example: license
        date_of_birth:
          type: string
          example: YYYY-MM-DD
        uploadFile:
          type: string
          format: binary
    pan:
      required:
        - uploadFile
        - pan_number
        - document_type
      type: object
      properties:
        pan_number:
          type: string
          example: J********
        document_type:
          type: string
          example: pan
        uploadFile:
          type: string
          format: binary
    business_proof:
      required:
        - uploadFile
        - document_type
      type: object
      properties:
        number:
          type: string
          example: 7**********1
        document_type:
          type: string
          example: >-
            Copy of LLP or Partnership Deed duly stamped and executed with
            Certificate of Incorporation. Deed will indicate names of partners
        uploadFile:
          type: string
          format: binary
    aadhaar_details:
      required:
        - dataFromAadhaar
      type: object
      properties:
        dataFromAadhaar:
          type: object
          required:
            - dob
            - name
            - gender
            - mobileHash
            - address
            - maskedAadhaarNumber
          properties:
            dob:
              type: string
              example: "1995-04-12"
            name:
              type: string
              example: Purnendra Ahirwar
            gender:
              type: string
              example: M
            mobileHash:
              type: string
              example: b274432d3427b977e40deff5e6aaaf0e5c7701336d1ea0b819f9c0fc5dee26e9
            address:
              type: object
            maskedAadhaarNumber:
              type: string
              example: XXXX XXXX 5428
